# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: March Machine Learning Madness 
email: f.saidmur@gmail.com
description:
  In Anton Chekhov's 1894 short story, "The Student", Ivan Velikopolsky is heading home
  during a cold March evening. He just left from an encounter with a friend, Vasilisa, who began to cry 
  bitterly when he told her the Biblical story about Peter's betrayal that occured 1,900 years ago.
  
  And in that moment, he realized that it wasn't the way he told the story that moved her,
  but rather the guilt that Peter himself felt that brought forward this emotion from Vasilisa.
  
  To the dead trees of the Russian winter, the clerical student said aloud,
  
  'the past... is linked with the present by an unbroken chain of events flowing one out of another'

  "... it seemed to him that he had just seen both ends of that chain; that when he touched one end the
  other quivered."

  This chain that Chekhov wrote of is spoken about by numerous Philisophers and Mathematicians throughout history.
  And most famously, by the French father of statistics, Pierre Simon de-Laplace.

  He wrote, 

  "Present events are connected with preceding ones by a tie based upon the evident principle that a thing cannot occur
  without a cause which produces it."

  He further postulated that if there was such a being that knew the present state of every single granularity of the Univerise, atoms,
  then this being would be able to perfectly predict the future and retrace the past with extreme accuracy.

  It is only appropriate then that field of computational statistical learning emerged as a way to predict outcome on historical data. This has made 
  some exciting developments, like for example image-classification, self-driving cars, and netflix recommendations. 

  But is this a sufficient mode of prediction when we start to introduce the most unpredictable element of the universe, humans?

  It's definitely a lucrative question, Warren Buffet once promised 1 Billion dollars for the individual that can generate a perfect March Madness bracket.

  Now that Sports Betting is legal, I present my March Madness predictions that my algorithm generated from historical ranking data. The methodology is further explained in the README. 

  And just to see how wrong my algorithm was, I present a number of other methods to predict the outcome of a college basketball game between two teams,
    - Winner is predicted to have stronger mascot 
    - Winner is predicted to have more popular team color 
    - Winner is predicted to be the tallest team

  I hope to generate the following questons in the reader,
    - Does everything have a predictive model?
    - Is all data predictive?
    - Can human generated data be used in models?
    - Is it better to sometimes guess than use a sophisticated (but wrong) model. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FarukhS6
github_username:  F-said

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
